### ISSUE TITLE
Address issue when trying it out

### ISSUE THREAD

**Issue by filipsch** [krvajal/release-bot#66]
So I tried the `release-bot` software.
On the repo https://github.com/sweepbright/github-admin, there is a [PR](https://github.com/sweepbright/github-admin/pull/1) that is in the "New Issues" pipeline.

The following `config.yml` therefore should work:

```yaml
zenhub:
  board_id: "191731526"
  to_deploy_pipeline: "New Issues"
github:
  repo: 'github-admin'
  owner: 'sweepbright'
```

However, this is the error I get:

```
$ node bot.js test_release
(node:51302) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at zenhubClient.getBoard.then.then.then.then.then.then.then.catch.err (/Users/filip/workspace/release-bot/bot.js:89:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:51302) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:51302) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Probably I'm doing something wrong, but it is not clear what :)

You should be able to try this as well, as you have all the permissions you need, I think.

**Comment by krvajal** [comment]
I just tried out your configuration and it works 
https://github.com/sweepbright/github-admin/pull/2

**Comment by filipsch** [comment]
My `ZENHUB_TOKEN` was called `ZENHUB_PAT`. I feel stupid, but indeed error could've been more informative. I'll try again with another PR and close if it works.

**Comment by filipsch** [comment]
```
➜  release-bot git:(master) ✗ node bot.js test_release
✔ Getting release pipeline
✔ Getting issues in release pipeline
✔ Filtering down the PRs
✔ Creating the release branch
✔ Creating the release branch
✔ Changing PR #3 base to release branch
✔ Creating PR from the release branch into master
ℹ https://github.com/sweepbright/github-admin/pull/4
✔ DONE!
```

beautiful :)
